	var jobs = [
		{
			name: "Callcenter medewerker NIB Incasso",
			shortName: "CC medew.",
			periode: "dec 1997 - mei 2001",
			description: ["Als student is hij begonnen bij het Nationaal Incasso Bureau om in de avonduren zijn studie te bekostigen. Hij is begonnen in de avondgroep en heeft later ook de leiding gekregen over deze groep.", "Als callcentermedewerker was het zijn verantwoordelijkheid om de telefoon te beantwoorden en vragen van debiteuren te beantwoorden. Ook had hij zijn eigen lijst met debiteuren die hij beheerdde. Hier had hij regelmatig contact mee, maakt afspraken over betalingen, trof regelingen en zorgde ervoor dat er een oplossing kwam die voor klant en debiteur acceptabel waren.", "Betalingsachterstanden zijn soms het gevolg van vergetenheid, maar vaak ligt er ook een diepere oorzaak aan ten grondslag. Dat betekent dat je naast debiteurenbeheerder ook soms sociaal werker bent. Markus heeft dan ook niet alleen contact met debiteuren maar ook vaak met bemiddelaars, schuldhulp en instanties om op die manier tot een oplossing te komen."],
			tools: ["Communicatie", "Overtuigen", "Overreden", "Luisteren", "Inschattingsvermogen", "oplossingsgericht"],
			indexVan: 100,
			subSet: 1,
			myclass: "j1",
			row1: true
		},
		{
			name: "Teamleider Callcenter avondploeg",
			shortName: "Teamleider",
			periode: "jan 1999 - mei 2001",
			description: ["Markus was destijds werkzaam als medewerker voor het Callcenter van het Nationaal Incasso Bureau en werkte van 13:00 tot :21:00. De teamleider stapte over van Collections naar Legal en we werden geconfronteerd met een team zonder directe leiding.","Markus werd gevraagd om deze taak te gaan vervullen. De verantwoordelijkheden van Markus waren de kwaliteit en productiviteit van de groep te waarborgen. Verder diende Markus als vraagbaak en hielp hij bij lastige casus.", "Onder leiding van Markus heeft de avondploeg goede resultaten geboekt en hebben wij tijd vrij weten te maken om ook mee te helpen aan de achterstanden van medewerkers die overdag werken.", "Dit was de eerste kennismaking met leidinggeven voor Markus. Hij heeft het kunnen helpen en begeleiden van de medewerkers als zeer bevredigend ervaren."],
			tools: ["Teamlead"],
			indexVan: 110,
			subSet: 1,
			row1: false,
			myclass: "j1s1"
		},
		{
			name: "ICT Medewerker NIB Incasso",
			shortName: "ICT medew",
			periode: "mei 2001 - jun 2008",
			description: ["Na vier jaar werd ik benaderd door de ICT manager met de vraag of ik niet zou willen overstappen naar de IT afdeling. Mijn IT vaardigheden en interesse in IT waren aanleiding om mij te vragen. Eerst in deeltijd om te zien of het bevalt en uiteindelijk voltijd werkzaam als IT medewerker.","Als ICT afdeling voor de NIB Group waren drie IT medewerkers verantwoordelijk voor het volledig beheer van de IT diensten voor 4 werkmaatschappijen. Alle IT werd intern gedaan.", "In deze tijd heb ik een aantal bijzondere projecten gedaan zoals het opzetten van het intranet, upgraden van de Novell server, implementeren van een nieuw incassopakket"],
			tools: [],
			indexVan: 200,
			subSet: 2,
			myclass: "j2",
			row1: true
		},
		{
			name: "Business Intelligence Specialist",
			shortName: "BI sepcialist",
			periode: "jan 2004 - jun 2008",
			description: ["Het Nationaal Incasso Bureau is een groot (inter)nationaal incassobureau dat zowel voor interne en externe doeleinden rapportages nodig had. Veel rapportages werden voordien op omslachtige manieren in Excel en Word geproduceerd. Het betrof meerdere grote projecten en rapportages.", "In de eerste fase van de projecten was het de taak van Markus om in overleg met het management en de directie de juiste informatiebehoeften in kaart te brengen. Dit gebeurde aan de hand van overleg en verkenning van de huidige rapportages.", "Hierna was het de taak van Markus om middels Data Mining de data die voorhanden was te onderzoeken en te controleren op consistentie, zodoende er voor te zorgen dat de benodigde data uiteindelijk ook voor handen was. Indien de data niet voorhanden was diende deze alsnog  beschikbaar gesteld te worden in een view of tijdelijke database. Met deze data werden de rapportages ontwikkeld in Crystal Reports 9, Crystal Reports 11 of Business Objects 6.", "De laatste fase van de projecten bestond uit terugkoppeling naar management en directie, eventuele aanpassingen en presentatie van de rapportages.", "Alle rapportages zijn nadien onder beheer gebleven van Markus die ook verdere ontwikkeling en uitbreiding van de rapportages voor zijn rekening nam."],
			tools: ["Business Object", "Crystal Reports", "Oracle Database", "Advantage Database", "Clipper" ,"Data mining", "Business Intelligence"],
			indexVan: 220,
			subSet: 2,
			myclass: "j2s2",
			row1: false
		},
		{
			name: "Vervanger ICT Manager",
			shortName: "Vervanger manager",
			periode: "jan 2003 - jun 2008",
			description: [],
			tools: [],
			indexVan: 230,
			subSet: 2,
			myclass: "j2s3",
			row1: false
		},
		{
			name: "Frontend Developer",
			shortName: "Frontend Developer",
			periode: "mrt 2006 - jun 2008",
			description: ["Een van de taken als ICT medewerker was het onderhouden van de websites van de NIB groep. Markus onderhield de websites voor vier van de onderliggende ondernemingen:</br ><ul class=\"normal\"><li>&raquo; NIB Incasso</li><li>&raquo; NIB Juristen</li><li>&raquo; TCM Nederland</li><li>&raquo; NRB Creatieve Communicatie</li></ul>", "De websites waren gebouwd in MODx CMS. De websites waren geheel in eigen beheer. Wijzigingen waren op het gebied van de pagina's, opmaak van de website en het up-to-date houden van de CMS.", "Binnen het Nationaal Incasso Bureau was veel kennis en informatie aanwezig alleen is deze nooit centraal opgeslagen geweest. Bij het uit dienst treden van medewerkers kwam het dan ook voor dat kennis verloren ging. Het management wilde hier een oplossing voor hebben. Na het aandragen van het idee intranet, werd Markus gevraagd het idee uit te werken en vorm te geven.", "Hij heeft het gehele proces van het verzamelen van de informatie tot het uiteindelijke verwerken van de informatie in een door hem ontwikkeld en ontworpen intranet. Uiteindelijk heeft Markus het Intranet ook vernieuwd en in een portal gebouwd. Xoops is in eerste instantie gebruikt als portal, later is een ander opensource portal gebruikt - ModxCMS."],
			tools: ["HTML", "CSS", "Apache", "Xoops", "CMS"],
			indexVan: 240,
			subSet: 2,
			myclass: "j2s4",
			row1: false
		},
		{
			name: "Business Intelligence Consultant",
			shortName: "BI Consultant",
			periode: "jun 2008 - mei 2010",
			description: ["Ik heb ruim 10 jaar ervaring met Business Intelligence, datawarehousing en ETL processen. Vanaf 2003 ben ik intensief bezig geweest met Business Intelligence. Ik heb mijzelf het vak eigen gemaakt en ben begonnen met Crystal Reports op een Advanced Database. Daarna overgestapt naar Business Objects op SQL en Oracle databases. Naast rapporten maken zorgde ik ook voor de datastromen en de datawarehouses, universes en ETL processen.", "Niet alleen op het vlak van ontwikkelaar ben ik bezig geweest met BI. Ik ben bestuurder geweest van het Atos Business Objects Competence Team waar wij aanspreekpunt waren voor alle zaken op het gebied van Business Objects, Crystal Reports en XCelsius. Ook heb ik een project begeleid om de juiste keuze te maken voor een BI tool.", "Tenslotte heb ik junior medewerkers opgeleid tot volwaardige BI experts.", "Mijn kennis komt ook pas bij de CICD coaching. Enkele BI en ETL teams vallen momenteel onder mijn hoede."],
			tools: [],
			indexVan: 300,
			subSet: 3,
			myclass: "j3",
			row1: true
		},
		{
			name: "Coach and guide junior BI specialists",
			shortName: "coach BI Juniors",
			periode: "okt 2009 - okt 2013",
			description: ["As a senior BI specialist Markus has coached, trained and supervised multiple junior specialists in the areas of Oracle, Crystal Reports and Business Objects. The responsibilities of Markus were to increase the quality, employability and knowledge of the employees. "],
			tools: ["Business Objects", "BO WEBI", "Business Object Universe designer", "Toad", "Softerra LDAP Administrator", "Shell Script", "Knowledge sharing", "Coaching"],
			indexVan: 310,
			subSet: 3,
			myclass: "j3s1",
			row1: false
		},
		{
			name: "Bestuurslid Business Objects Kernteam - Atos Origin",
			shortName: "BO kernteam",
			periode: "mrt 2009 - sep 2011",
			description: ["Binnen Atos Origin BI/CRM zijn er competance teams die de kennis tot een bepaald onderwerp moeten borgen. Eén van deze teams is het Business Objects kernteam.", "Wij ondersteunen het management in opleiding, certificering, kennisborging en inventarisering met betrekking tot Business Objects, Excelsius en Crystal Reports.", "Tevens fungeren wij als brug naar SAP als bedrijf en de SAP afdeling binnen Atos Origin.", "Binnen het team heeft Markus de taak om zich vooral op het gebied van Crystal Reports de taken van het team te vervullen."],
			tools: [],
			indexVan: 320,
			subSet: 3,
			myclass: "j3s2",
			row1: false
		},
		{
			name: "Advies Business Intelligence tool - ING",
			shortName: "Adviseur tool keuze",
			periode: "sep 2008 - okt 2008",
			description: ["Project Terabyte heroverwoog de eerste keuze van Crystal Reports af te stappen als rapportage tool. De bedoeling was de tool in een nieuw te ontwikkelen .NET applicatie te bouwen. Het project stelde eisen aan de tool om bestuurbaar te zijn vanuit de .NET applicatie.", "Het was aan Markus om een advies uit te brengen over de juiste rapportage tool voor het project.", "Op basis van de gestelde eisen heeft Markus een aantal interviews afgenomen met de verschillende onderdelen van het team. BI, Tooling, management werden gehoord.", "Met de afgenomen interviews en de opgestelde eisen van de verschillende teamleden heeft Markus een eerste opzet gemaakt met een tijdkelijk advies.", "In een vergadering werd daar op ingezoemd en werden eventuele nieuwe vragen en opmerkingen verzameld zodat deze in het uiteindelijke advies gepresenteerd konden worden.", "Uiteindelijk is het advies gepresenteerd en overgenomen door het projectteam."],
			tools: [],
			indexVan: 330,
			subSet: 3,
			myclass: "j3s3",
			row1: false
		},
		{
			name: "Business Objects Expert",
			shortName: "BO Expert",
			periode: "jun 2008 - jun 2011",
			description: ["ING - Entitlement Services - maakt gebruik van IBM Tivoli Identity Manager om rechten en rollen van medewerkers toe te kennen, te beheren en te verwijderen. Voor controle mechanismes is een Business Objects omgeving opgezet. Binnen deze omgeving zijn drie verschillende rapportages gebouwd. Te weten. <br /><ul class=\"normal\"><li>&raquo; vrij opvraagbaar door managers met de mogelijkheid zelf te verversen en dataselecties te maken middels een prompt.</li><li>&raquo; vrij opvraagbaar door managers met een vast geplande verversing.</li><li>&raquo; rapportages die automatisch ververst worden en via mail eens per periode verstuurd worden.</li></ul>", "Het was de taak van Markus om de gehele omgeving te beheren. De taken van Markus bestonden uit een drietal hoofdzaken:<br /><ul class=\"normal\"><li>Ten eerste was Markus verantwoordelijk voor het onderhoud aan de Universe en bestaande rapportages. Onderhoud in de ruimste zin van het woord. Niet alleen up to date houden van rapportages en Universes, maar ook bijhouden van documentatie, bijhouden versie beheer en beantwoorden vragen van de klant omtrend de rapportages.</li><li>Ten tweede was het zijn taak om samen met de gebruiker nieuwe en/of betere rapportages te verzorgen. Dit deel van zijn takenpakket behelsde een informatie analyse sessie met de klant, vervolgens het ontwerp en ontwikkelen van de rapportage. Nadat de rapportage klaar was werd deze samen met de klant geevalueerd en gecontroleerd. Als alles in orde was werd de juiste vorm van publicatie gekozen en werd het rapport in productie genomen.</li><li>Als laatste was Markus betrokken in vergaderingen en overleggen welke betrekking hadden op Entitlement Services en (mogelijke) rapportages. Zijn expertise op het gebied van Business Intelligence, Business Objects en de data omgeving gold als input voor openstaande vraagstukken. </li>"],
			tools: ["Business Objects", "BO WEBI", "Business Object Universe designer", "Toad", "Change management", "DTAP", "Data Mining", "Testing"],
			indexVan: 340,
			subSet: 3,
			myclass: "j3s4",
			row1: false
		},
		{
			name: "Identiy and Access Management Specialist",
			shortName: "IAM Consultant",
			periode: "jun 2008 - heden",
			description: ["Ik ben een enthousiaste ICT consultant en inmiddels ruim 8 jaar werkzaam bij Atos. ik ben analytisch en vindt het leuk om nieuwe dingen te leren. Een uitdaging ga ik niet uit de weg en help graag een ander om het beste uit zich zelf te halen.","Mijn inzet en toewijding hebben mij geholpen om mijn werkgebied uit te breiden van ICT medewerker, naar SAP Business Intelligence specialist, Competence team bestuurder, change- release co&#246;rdinator, vervangend teamleider en uiteindelijk een plaats in het Atos talenten programma.","De laatste jaren heb ik veel ervaring opgedaan met Agile, Scrum en ITIL. De opgedane kennis wil ik graag overdragen en gebruiken bij onze opdrachtgevers.","Ik ben analytisch, enthousiast en denk vanuit het perspectief van de opdrachtgever. Ik werk graag samen, ben in staat me eenvoudig aan mijn omgeving aan te passen, toon initiatief en ben erg leergierig."],
			tools: [],
			indexVan: 400,
			subSet: 4,
			myclass: "j4",
			row1: true
		},
		{
			name: "Consultant Risk & Security - ING",
			shortName: "Consultant Risk/Security",
			periode: "okt 2015 - dec 2015",
			description: ["As a Consultant Risk & Security Markus advised on securing critical information and business processes at the strategic, tactical and operational level. He was the bridge between Business, IT and Risk departments whom could explain technical challenges at all levels. He monitored the set of practices that focuses on aligning IT services with the needs of business (ITIL). He also helped design and / or implementation processes that ensure the continuity of User Access in case of incidents or a crisis.", "Security in the areas of confidentiality, integrity and availability dominated in the User Access area. Markus was responsible for five applications. In the three months that he shared his vision, he has substantially increased the security of the applications. He did this by: <ul class=\"normal\"> <li>&raquo; Designing password reset procedures for High Privileged Accounts;</li><li>&raquo; Designing Security Event Monitoring;</li><li>&raquo; Resolve audit / security findings;</li><li>&raquo; Writing security and compliance documents;</li><li>&raquo; Improvement plans require security risks.</li></ul>"],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "CMDB", "Aveksa", "Scrum", "DevOps", "Backup and Restore", "Disaster Recovery", "Governance", "Security Event Monitoring", "Security", "HPSC", "Operational Security Guidelines", "Identity- and  Access Management", "Dynamic/Static Code review", "Auditing", "ITIL"],
			indexVan: 410,
			subSet: 4,
			myclass: "j4s1",
			row1: false
		},
		{
			name: "Scrum Master DevOps Authentication - ING",
			shortName: "Scrum master",
			periode: "dec 2014 - sep 2015",
			description: ["As scrum master Markus facilitated the scrum method, he was accountable for removing impediments to the ability of the team to deliver the product goals and deliverables. He acted as a buffer between the team and any distracting influences. He ensured that the scrum process is used as intended. He helped ensure the team follows the agreed scrum processes, often facilitated key sessions, and encouraged the team to improve. His role could also been referred to as a team facilitator or servant-leader to reinforce these dual perspectives.","Markus his core responsibilities as scrum master included: <ul class=\"normal\"> <li>&raquo; Helping the product owner maintain the product backlog in a way that ensures the needed work is well understood so the team can continually make forward progress</li><li>&raquo; Helping the team to determine the definition of done for the product, with input from key stakeholders</li><li>&raquo; Coaching the team, within the scrum principles, in order to deliver high-quality features for its product</li><li>&raquo; Promoting self-organization within the team</li><li>&raquo; Helping the scrum team to avoid or remove impediments to its progress, whether internal or external to the team</li><li>&raquo; Facilitating team events to ensure regular progress</li><li>&raquo; Educating key stakeholders in the product on scrum principles", "Together with the team he has set up the infrastructure for a PAAS environment, implemented workflows and he has built connections to different platforms (e.g. CDS. AD, RACF, Unix) for automatic provisioning.", "The team was responsible for the whole DTAP environment. All code / configurations were developed by the team, tests have been developed and implemented - partly automated and partly manual. Eventually the final product, after approval of the Product Owner, was implemented on production and managed. The operational part of the team gave input for development in upcoming sprints.", "In addition to his responsibilities to the team, he worked close together with the Product Owner to ensure that the user stories were ready and clear for the upcoming sprints."],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "HPSC", "CMDB", "Aveksa", "GIT", "Fitnesse", "Selenium", "WebEx", "Incident Management", "Oracle Enterprise Manager", "Websphere Console", "NetBeans IDE", "SSH", "Notepad++", "Oracle SQL Developer", "Softerra LDAP Administrator", "Putty", "Scrum", "DevOps", "Backup and Restore", "Security Event Monitoring", "Java", "Auditing", "ITIL", "Operational Security Guidelines", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "Data masking", "Testing", "Applicatie beheer", "Operationeel beheer", "JBoss", "Coaching", "Javascript", "HTML", "VBscript", "Shell Script", "Oracle", "WebSphere"],
			indexVan: 420,
			subSet: 4,
			myclass: "j4s2",
			row1: false
		},
		{
			name: "Product Owner Scrumteams - ING",
			shortName: "Product Owner",
			periode: "mei 2014 - nov 2014",
			description: ["Markus gathered input from stakeholder, data analysis and feedback from the business. And in the meantime he developed/improved a vision for his focus area (Aveksa). The gathered input and vision was transform into a roadmap and a backlog. Together with his team, he was responsible for executing and delivering a reliable User Access Management environment.", "Markus was responsible for two scrum teams. His team consisted of developers, Operational staff, business analysts and architects. Together they improved and renewed, in the sprints, the  applications for the User Access Management environment. And as Product Owner Markus together with the team and the stakeholders set the direction for the focus."],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "HPSC", "Aveksa", "GIT", "WebEx", "IBM Tivoli Identity Manager", "Scrum", "DevOps", "Backup and Restore", "Auditing", "ITIL", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "Testing", "Applicatie beheer", "Operationeel beheer", "Incident Management", "Roadmap"],
			indexVan: 430,
			subSet: 4,
			myclass: "j4s3",
			row1: false
		},
		{
			name: "Identity- Access en Security Specialist in DevOps / Scrum team  - ING",
			shortName: "Dev engineer DevOps",
			periode: "sep 2013 - sep 2015",
			description: ["After being involved for more than more than five years within the Identity- Access Management solution for ING's Markus was asked to join the scrum team to implement a new Identity- Access Management product. His extensive experience with the processes, current technology and procedures made him an excellent addition to the team.", "Markus fulfilled multiple roles within the Scrum team that evolved to a DevOps team.", "connections to different platforms (CDS; AD; RACF; Unix) and created rules to automate authorization management. Together with the team he managed an appliance and later converted the appliance to a PAAS environment. The team was responsible for the content of the database (Oracle) and the filesystem (Unix), the middleware (JBoss on the appliance and WebSphere on PAAS) and Life Cycle management of the application..", "As operational engineer Markus participated in the sergeant roaster. For a day per 2 weeks Markus was responsible for daily checks, incidents and email. Markus had a key role in change management. He created changes and monitored them to make sure the releases followed the ING procedures. He made sure tests were done and reviewed the results. He advised the Product Owner in approvals.  "],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "HPSC", "CMDB", "Aveksa", "GIT", "Fitnesse", "Selenium", "WebEx", "Oracle Enterprise Manager", "Websphere Console", "NetBeans IDE", "Notepad++", "Oracle SQL Developer", "Softerra LDAP Administrator", "Putty", "IBM Tivoli Identity Manager", "Entitlement Account Administrator", "Scrum", "DevOps", "Backup and Restore", "Security Event Monitoring (SEM)", "Auditing", "ITIL", "Operational Security Guidelines (OSG)", "Identity- and  Access Management (IAM)", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "SSH", "SFTP", "SSL", "Data masking", "Testing", "Application management", "Operational management", "Incident Management", "Javascript", "Java", "HTML", "VBAscript", "Shell Script", "Oracle", "WebSphere", "JBoss", "DTAP;"],
			indexVan: 440,
			subSet: 4,
			myclass: "j4s4"
		},
		{
			name: "Teamleader Entitlement Services (CDC ING/UAS) - Atos",
			shortName: "Teamleider IAM dev team",
			periode: "sep 2011 - sep 2013",
			description: ["As a team leader Markus managed technical team of the Entitlement Services department. The team was responsible for ING's identity and access management application. He oversaw the activities of the team and coached both the team as individuals with the aim to get the best out of both. He also was responsible for HR tasks such as team meetings, face-to-face conversations and he organized GROW sessions.", "He was also responsible for setting up the change process and set up the planning thereof. He made sure that the occupation of the department was consistent to the workload.", "He supervised the SLA agreements, created reports and wrote the Service Component Description. Markus kept in close contact with ING in various discussions and linked the feedback back to his team.", "His role was coaching and consulting, he systematically applied the right structure and he had a strong vision of the production process. Through his dedication he brought not only his department at a higher level but he helped the organization as a whole ahead as well!  "],
			tools: ["Auditing", "ITIL", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "SSH", "Testing", "Applicatie beheer", "Operationeel beheer", "Incident Management", "Javascript", "Java", "HTML", "VBscript", "Oracle", "WebSphere", "GROW", "Service Component Description", "Human Resourcing", "Service Level Agreement", "Key Performance Indicators", "Coaching"],
			indexVan: 450,
			subSet: 4,
			myclass: "j4s5",
			row1: false
		},
		{
			name: "Change- en Release Coordinator ITIM - Atos",
			shortName: "Change- release mgr",
			periode: "mrt 2011 - okt 2013",
			description: ["In this assignment as change Coordinator at the CDC ING Markus manages the development team, changes and releases. The team maintained IBM Tivoli Identity Manager (ITIM) for ING. Atos maintained the application; workflows; adapters to different platforms; the Java shell for end users and the reports. These were all subject to changes. Markus maintained direct contact with the functional owner of ITIM, is present in the Change Advisory Board, manages the team and made the release planning.", "Markus maintained contact with the different departments of Atos UAS. Within the release planning he handled resource planning, end-to-end test planning, maintenance of DTA-environments and DTA release planning. "],
			tools: ["SDM", "Office", "SharePoint", "HP Service Center", "IBM Tivoli Identity Manager", "Governance", "Auditing", "ITIL", "Incident Management", "Release Management", "DTAP" ],
			indexVan: 460,
			subSet: 4,
			myclass: "j4s6",
			row1: false
		},
		{
			name: "Agile Software Development Coach",
			shortName: "Agile Coach",
			periode: "jan 2016 - Heden",
			description: ["Tussen 2013 en 2016 ben ik nauw betrokken geweest bij een Scrum project binnen ING. Als Product Owner en Scrum Master heb ik geholpen het Scrum proces in te richten binnen de User Access afdeling. Deze ervaring, die ik heb opgedaan binnen DevOps ING, kan ik goed gebruiken voor de invulling van de rol van Agile Coach bij toekomstige opdrachten.","Als Scrum Master, Mentor van een aantal projecten en als teamleider zijn vooral mijn coachende vaardigheden ontwikkeld. Ik heb onder andere junior medewerkers geholpen zich te ontwikkelen tot BI specialisten en ge&#239;nspireerd zich te blijven verbeteren op hun vakgebied. E&#233;n van mijn grootste projecten was als Mentor van een mindset verander traject, hier heb ik een groep van 250 managers en 5000 medewerkers gecoacht om een grootschalige cultuur omslag te maken. Als Scrum Master heb ik bewezen dat ik een Scrum Team kan coachen in de principes van Agile/Scrum en zorgde ik ervoor dat het team het juiste Scrum proces volgde.","Ik ben een groot fan van de Agile manier van werken. Binnen Atos heb ik het management ge&#239;nspireerd op een Agile manier te werken. Mede hierdoor ontstonden op meerdere strategische niveaus Scrum Teams, die onderling samenwerkten om de visie van een klant specifiek opleidingsproject waar te maken. Het bereiken van dit resultaat gaf mij veel voldoening"],
			tools: [],
			indexVan: 500,
			subSet: 5,
			myclass: "j5",
			row1: true
		},
		{
			name: "Agile coach CI/CD Stack - Nationale Nederlanden",
			shortName: "Agile CI/CD Coach",
			periode: "jan 2018 - now",
			description: ["no text yet"],
			tools: ["Jira", "Office", "Jenkins", "SonarQube", "HP Fortify", "Maven", "Scrum", "DevOps", "Agile", "Consulting", "Interview", "Knowledge transfer", "Coaching", "Continuous Integration", "Continuous Delivery", "Unit testing", "Code Quality", "VBA", "Bootcamps", "Workshops", "XL Release", "XL Deploy", "uDeploy"],
			indexVan: 550,
			subSet: 5,
			myclass: "j5s5",
			row1: false
		},
		{
			name: "Agile coach CI/CD Stack - ABN Amro",
			shortName: "Agile CI/CD Coach",
			periode: "jun 2016 - dec 2018",
			description: ["Within IT Solutions a CI/CD (Continuous Integrations / Continuous Delivery) Expert was needed, who has, next to his technical expertise, also great coaching skills.", "A Centers of Expertise (CoE) collaborates with projects to ensure that new or modified applications and infrastructure are implemented correctly. This makes the role of the CoE staff in a project highly complex. Partly the project is assisted by expertise from the CoE, on the other hand, of the other part, regulations and governance that need to be followed can be a complicating and restricting factor for the project. Extra factor is that they are also part of the formal Quality Assurance in their own jurisdiction.", "Upon Markus' arrival Agile / Scrum was rolled out in certain parts of the bank, in addition to attitude and behaviour is automation of processes conditionally for a successful rollout.", "As Agile coach CI/CD Stack Markus was responsible for:<ul class=\"normal\"> <li>&raquo; Coaching</li><li>&raquo; Flexibility and inventiveness</li><li>&raquo; IT authority</li></ul>"],
			tools: ["Jira", "Office", "Jenkins", "SonarQube", "HP Fortify", "Maven", "Scrum", "DevOps", "Agile", "Consulting", "Interview", "Knowledge transfer", "Coaching", "Continuous Integration", "Continuous Delivery", "Unit testing", "Code Quality", "VBA", "Bootcamps", "Workshops", "XL Release", "XL Deploy", "uDeploy"],
			indexVan: 510,
			subSet: 5,
			myclass: "j5s1",
			row1: false
		},
		{
			name: "Agile coach and adviseur - Atos",
			shortName: "Agile CI/CD Coach",
			periode: "jan 2016 - jun 2016",
			description: ["As Agile coach Markus promoted and advised on the agile way of work within Atos and at several clients.", "Starting in a start-up innovations team from where Markus used his experience with scrum and DevOps to streamline the scrum process. He gave an agile fundamentals training which inspired people to broaden their knowledge even further and resulted in some of them preparing for their own PSM1 certificate.", "For several clients Markus analysed the current agile processes and identified bottlenecks. He advised how to solve the bottlenecks and wrote plans to improve the current processes. For one of the clients he even set up a complete plan to incorporate the business within the DevOps structure.", "At Atos Internally Markus has supported a group of managers to create a client specific training project using the Scrum framework. He provided structure so the top management would engage the portfolio and roadmap, a second level of managers were working out their own specific areas. In this way several Scrum teams were created. Markus safeguarded the Scrum methodology and helped to establish a Jira board. "],
			tools: ["Jira", "Office", "Scrum", "DevOps", "Agile", "Consulting", "Interview" ,"Knowledge transfer" , "Coaching"],
			indexVan: 520,
			subSet: 5,
			myclass: "j5s2",
			row1: false
		},
		{
			name: "Mentor \"Transforward to .....\" Project - Atos",
			shortName: "Mentor change project",
			periode: "apr 2014 - dec 2014",
			description: ["Trans Forward to ..... was a large project to trigger an internal change in culture and mind-set among staff of Managed Services. The whole project consisted of three phases.<ul class=\"normal\"><li>&raquo; Trans forward to Connect;</li><li>&raquo; Trans forward to Shape;</li><li>&raquo; Trans forward to Change.</li></ul>", "In total an organization of around 5000 people had to change. This was done by letting the Management Team, all managers and 1500 employees engage the change process within the organization.", "methods:<ul class=\"normal\"><li>&raquo; Awareness sessions</li><li>&raquo; Open Space sessions</li><li>&raquo; Process improvement projects</li></ul>", "As one of the mentors Markus made sure that the Management Team, all managers of Managed Services and a large group of employees were led through these phases. Besides being involved in all sessions, he was closely involved in all activities outside of the sessions. It was his job to coach participants and let them stay aware of the objectives and commitments.", "As mentor team together with the coaches we have put up a great result. A Denison scan has revealed that the mind-set and culture change has been turned into in the right direction."],
			tools: ["Management Funnel", "Cultural Web Assessment", "SCARF Model", "Sfeer van Invloed", "Persoonlijksheidscirkel", "Interview", "Knowledge Transfer", "Coaching"],
			indexVan: 530,
			subSet: 5,
			myclass: "j5s3",
			row1: false
		},
		{
			name: "CDC ING Knowledge Motivator - Atos",
			shortName: "knowledge motivator",
			periode: "nov 2012 - okt 2013",
			description: ["Within the ING delivery Centre at Atos a training program was launched to improve the employees communication skills and make them more costumer minded. The project included a small group of people to keep the knowledge and tools in practice.", "As one of the motivators I was responsible for sharing knowledge to teammembers and make sure that the tools and methodes keep being used within the team.", "As a motivator Markus has learned a lot of personal effectiveness. To let the employees practice the learned skills Markus organized sessions. In this sessions they could use their newly learned skills in a familiar environment. Employees got the responsibility to organize these sessions as well got coached and were able to practice. "],
			tools: ["Office", "Lean", "Interview", "Knowledge transfer", "Coaching"],
			indexVan: 540,
			subSet: 5,
			myclass: "j5s4",
			row1: false
		}
	]
