	var jobs = [
		{
			name: "Callcenter medewerker NIB Incasso",
			shortName: "CC medew.",
			periode: "dec 1997 - mei 2001",
			description: ["Als student is hij begonnen bij het Nationaal Incasso Bureau om in de avonduren zijn studie te bekostigen. Hij is begonnen in de avondgroep en heeft later ook de leiding gekregen over deze groep.", "Als callcentermedewerker was het zijn verantwoordelijkheid om de telefoon te beantwoorden en vragen van debiteuren te beantwoorden. Ook had hij zijn eigen lijst met debiteuren die hij beheerdde. Hier had hij regelmatig contact mee, maakt afspraken over betalingen, trof regelingen en zorgde ervoor dat er een oplossing kwam die voor klant en debiteur acceptabel waren.", "Betalingsachterstanden zijn soms het gevolg van vergetenheid, maar vaak ligt er ook een diepere oorzaak aan ten grondslag. Dat betekent dat je naast debiteurenbeheerder ook soms sociaal werker bent. Markus heeft dan ook niet alleen contact met debiteuren maar ook vaak met bemiddelaars, schuldhulp en instanties om op die manier tot een oplossing te komen."],
			tools: ["Communicatie", "Overtuigen", "Overreden", "Luisteren", "Inschattingsvermogen", "oplossingsgericht"],
			indexVan: 100,
			subSet: 1,
			myclass: "j1",
			row1: true
		},
		{
			name: "Teamleider Callcenter avondploeg",
			shortName: "Teamleider",
			periode: "jan 1999 - mei 2001",
			description: ["Markus was destijds werkzaam als medewerker voor het Callcenter van het Nationaal Incasso Bureau en werkte van 13:00 tot :21:00. De teamleider stapte over van Collections naar Legal en we werden geconfronteerd met een team zonder directe leiding.","Markus werd gevraagd om deze taak te gaan vervullen. De verantwoordelijkheden van Markus waren de kwaliteit en productiviteit van de groep te waarborgen. Verder diende Markus als vraagbaak en hielp hij bij lastige casus.", "Onder leiding van Markus heeft de avondploeg goede resultaten geboekt en hebben wij tijd vrij weten te maken om ook mee te helpen aan de achterstanden van medewerkers die overdag werken.", "Dit was de eerste kennismaking met leidinggeven voor Markus. Hij heeft het kunnen helpen en begeleiden van de medewerkers als zeer bevredigend ervaren."],
			tools: ["Teamlead"],
			indexVan: 110,
			subSet: 1,
			row1: false,
			myclass: "j1s1"
		},
		{
			name: "ICT Medewerker NIB Incasso",
			shortName: "ICT medew",
			periode: "mei 2001 - jun 2008",
			description: ["Na vier jaar werd ik benaderd door de ICT manager met de vraag of ik niet zou willen overstappen naar de IT afdeling. Mijn IT vaardigheden en interesse in IT waren aanleiding om mij te vragen. Eerst in deeltijd om te zien of het bevalt en uiteindelijk voltijd werkzaam als IT medewerker.","Als ICT afdeling voor de NIB Group waren drie IT medewerkers verantwoordelijk voor het volledig beheer van de IT diensten voor 4 werkmaatschappijen. Alle IT werd intern gedaan.", "In deze tijd heb ik een aantal bijzondere projecten gedaan zoals het opzetten van het intranet, upgraden van de Novell server, implementeren van een nieuw incassopakket"],
			tools: [],
			indexVan: 200,
			subSet: 2,
			myclass: "j2",
			row1: true
		},
		{
			name: "Business Intelligence Specialist",
			shortName: "BI sepcialist",
			periode: "jan 2004 - jun 2008",
			description: ["Het Nationaal Incasso Bureau is een groot (inter)nationaal incassobureau dat zowel voor interne en externe doeleinden rapportages nodig had. Veel rapportages werden voordien op omslachtige manieren in Excel en Word geproduceerd. Het betrof meerdere grote projecten en rapportages.", "In de eerste fase van de projecten was het de taak van Markus om in overleg met het management en de directie de juiste informatiebehoeften in kaart te brengen. Dit gebeurde aan de hand van overleg en verkenning van de huidige rapportages.", "Hierna was het de taak van Markus om middels Data Mining de data die voorhanden was te onderzoeken en te controleren op consistentie, zodoende er voor te zorgen dat de benodigde data uiteindelijk ook voor handen was. Indien de data niet voorhanden was diende deze alsnog  beschikbaar gesteld te worden in een view of tijdelijke database. Met deze data werden de rapportages ontwikkeld in Crystal Reports 9, Crystal Reports 11 of Business Objects 6.", "De laatste fase van de projecten bestond uit terugkoppeling naar management en directie, eventuele aanpassingen en presentatie van de rapportages.", "Alle rapportages zijn nadien onder beheer gebleven van Markus die ook verdere ontwikkeling en uitbreiding van de rapportages voor zijn rekening nam."],
			tools: ["Business Object", "Crystal Reports", "Oracle Database", "Advantage Database", "Clipper" ,"Data mining", "Business Intelligence"],
			indexVan: 220,
			subSet: 2,
			myclass: "j2s2",
			row1: false
		},
		{
			name: "Vervanger ICT Manager",
			shortName: "Vervanger manager",
			periode: "jan 2003 - jun 2008",
			description: [],
			tools: [],
			indexVan: 230,
			subSet: 2,
			myclass: "j2s3",
			row1: false
		},
		{
			name: "Frontend Developer",
			shortName: "Frontend Developer",
			periode: "mrt 2006 - jun 2008",
			description: ["Een van de taken als ICT medewerker was het onderhouden van de websites van de NIB groep. Markus onderhield de websites voor vier van de onderliggende ondernemingen:</br ><ul class=\"normal\"><li>NIB Incasso</li><li>NIB Juristen</li><li>TCM Nederland</li><li>NRB Creatieve Communicatie</li></ul>", "De websites waren gebouwd in MODx CMS. De websites waren geheel in eigen beheer. Wijzigingen waren op het gebied van de pagina's, opmaak van de website en het up-to-date houden van de CMS.", "Binnen het Nationaal Incasso Bureau was veel kennis en informatie aanwezig alleen is deze nooit centraal opgeslagen geweest. Bij het uit dienst treden van medewerkers kwam het dan ook voor dat kennis verloren ging. Het management wilde hier een oplossing voor hebben. Na het aandragen van het idee intranet, werd Markus gevraagd het idee uit te werken en vorm te geven.", "Hij heeft het gehele proces van het verzamelen van de informatie tot het uiteindelijke verwerken van de informatie in een door hem ontwikkeld en ontworpen intranet. Uiteindelijk heeft Markus het Intranet ook vernieuwd en in een portal gebouwd. Xoops is in eerste instantie gebruikt als portal, later is een ander opensource portal gebruikt - ModxCMS."],
			tools: ["HTML", "CSS", "Apache", "Xoops", "CMS"],
			indexVan: 240,
			subSet: 2,
			myclass: "j2s4",
			row1: false
		},
		{
			name: "Business Intelligence Consultant",
			shortName: "BI Consultant",
			periode: "jun 2008 - mei 2010",
			description: ["Ik heb ruim 10 jaar ervaring met Business Intelligence, datawarehousing en ETL processen. Vanaf 2003 ben ik intensief bezig geweest met Business Intelligence. Ik heb mijzelf het vak eigen gemaakt en ben begonnen met Crystal Reports op een Advanced Database. Daarna overgestapt naar Business Objects op SQL en Oracle databases. Naast rapporten maken zorgde ik ook voor de datastromen en de datawarehouses, universes en ETL processen.", "Niet alleen op het vlak van ontwikkelaar ben ik bezig geweest met BI. Ik ben bestuurder geweest van het Atos Business Objects Competence Team waar wij aanspreekpunt waren voor alle zaken op het gebied van Business Objects, Crystal Reports en XCelsius. Ook heb ik een project begeleid om de juiste keuze te maken voor een BI tool.", "Tenslotte heb ik junior medewerkers opgeleid tot volwaardige BI experts.", "Mijn kennis komt ook pas bij de CICD coaching. Enkele BI en ETL teams vallen momenteel onder mijn hoede."],
			tools: [],
			indexVan: 300,
			subSet: 3,
			myclass: "j3",
			row1: true
		},
		{
			name: "Coachen en begeleiden junior medewerkers",
			shortName: "coach BI Juniors",
			periode: "okt 2009 - okt 2013",
			description: ["Als senior BI specialist heeft Markus in zijn tijd binnen Atos meerdere junior medewerkers op het gebied van Oracle, Crystal Reports en Business Objects gecoacht, begeleid en opgeleid. De verantwoordelijkheden van Markus waren de kwaliteit, inzetbaarheid en kennis van de medewerkers te vergroten."],
			tools: ["Business Objects", "BO WEBI", "Business Object Universe designer", "Toad", "Softerra LDAP Administrator", "Shell Script", "Kennisoverdracht", "Coaching"],
			indexVan: 310,
			subSet: 3,
			myclass: "j3s1",
			row1: false
		},
		{
			name: "Bestuurslid Business Objects Kernteam - Atos Origin",
			shortName: "BO kernteam",
			periode: "mrt 2009 - sep 2011",
			description: ["Binnen Atos Origin BI/CRM zijn er competance teams die de kennis tot een bepaald onderwerp moeten borgen. Eén van deze teams is het Business Objects kernteam.", "Wij ondersteunen het management in opleiding, certificering, kennisborging en inventarisering met betrekking tot Business Objects, Excelsius en Crystal Reports.", "Tevens fungeren wij als brug naar SAP als bedrijf en de SAP afdeling binnen Atos Origin.", "Binnen het team heeft Markus de taak om zich vooral op het gebied van Crystal Reports de taken van het team te vervullen."],
			tools: [],
			indexVan: 320,
			subSet: 3,
			myclass: "j3s2",
			row1: false
		},
		{
			name: "Advies Business Intelligence tool - ING",
			shortName: "Adviseur tool keuze",
			periode: "sep 2008 - okt 2008",
			description: ["Project Terabyte heroverwoog de eerste keuze van Crystal Reports af te stappen als rapportage tool. De bedoeling was de tool in een nieuw te ontwikkelen .NET applicatie te bouwen. Het project stelde eisen aan de tool om bestuurbaar te zijn vanuit de .NET applicatie.", "Het was aan Markus om een advies uit te brengen over de juiste rapportage tool voor het project.", "Op basis van de gestelde eisen heeft Markus een aantal interviews afgenomen met de verschillende onderdelen van het team. BI, Tooling, management werden gehoord.", "Met de afgenomen interviews en de opgestelde eisen van de verschillende teamleden heeft Markus een eerste opzet gemaakt met een tijdkelijk advies.", "In een vergadering werd daar op ingezoemd en werden eventuele nieuwe vragen en opmerkingen verzameld zodat deze in het uiteindelijke advies gepresenteerd konden worden.", "Uiteindelijk is het advies gepresenteerd en overgenomen door het projectteam."],
			tools: [],
			indexVan: 330,
			subSet: 3,
			myclass: "j3s3",
			row1: false
		},
		{
			name: "Business Objects Expert",
			shortName: "BO Expert",
			periode: "jun 2008 - jun 2011",
			description: ["ING - Entitlement Services - maakt gebruik van IBM Tivoli Identity Manager om rechten en rollen van medewerkers toe te kennen, te beheren en te verwijderen. Voor controle mechanismes is een Business Objects omgeving opgezet. Binnen deze omgeving zijn drie verschillende rapportages gebouwd. Te weten. <br /><ul class=\"normal\"><li>vrij opvraagbaar door managers met de mogelijkheid zelf te verversen en dataselecties te maken middels een prompt.</li><li>vrij opvraagbaar door managers met een vast geplande verversing.</li><li>rapportages die automatisch ververst worden en via mail eens per periode verstuurd worden.</li></ul>", "Het was de taak van Markus om de gehele omgeving te beheren. De taken van Markus bestonden uit een drietal hoofdzaken:<br /><ul class=\"normal\"><li>Ten eerste was Markus verantwoordelijk voor het onderhoud aan de Universe en bestaande rapportages. Onderhoud in de ruimste zin van het woord. Niet alleen up to date houden van rapportages en Universes, maar ook bijhouden van documentatie, bijhouden versie beheer en beantwoorden vragen van de klant omtrend de rapportages.</li><li>Ten tweede was het zijn taak om samen met de gebruiker nieuwe en/of betere rapportages te verzorgen. Dit deel van zijn takenpakket behelsde een informatie analyse sessie met de klant, vervolgens het ontwerp en ontwikkelen van de rapportage. Nadat de rapportage klaar was werd deze samen met de klant geevalueerd en gecontroleerd. Als alles in orde was werd de juiste vorm van publicatie gekozen en werd het rapport in productie genomen.</li><li>Als laatste was Markus betrokken in vergaderingen en overleggen welke betrekking hadden op Entitlement Services en (mogelijke) rapportages. Zijn expertise op het gebied van Business Intelligence, Business Objects en de data omgeving gold als input voor openstaande vraagstukken. </li>"],
			tools: ["Business Objects", "BO WEBI", "Business Object Universe designer", "Toad", "Change management", "DTAP", "Data Mining", "Testing"],
			indexVan: 340,
			subSet: 3,
			myclass: "j3s4",
			row1: false
		},
		{
			name: "Identiy and Access Management Specialist",
			shortName: "IAM Consultant",
			periode: "jun 2008 - heden",
			description: ["Ik ben een enthousiaste ICT consultant en inmiddels ruim 8 jaar werkzaam bij Atos. ik ben analytisch en vindt het leuk om nieuwe dingen te leren. Een uitdaging ga ik niet uit de weg en help graag een ander om het beste uit zich zelf te halen.","Mijn inzet en toewijding hebben mij geholpen om mijn werkgebied uit te breiden van ICT medewerker, naar SAP Business Intelligence specialist, Competence team bestuurder, change- release co&#246;rdinator, vervangend teamleider en uiteindelijk een plaats in het Atos talenten programma.","De laatste jaren heb ik veel ervaring opgedaan met Agile, Scrum en ITIL. De opgedane kennis wil ik graag overdragen en gebruiken bij onze opdrachtgevers.","Ik ben analytisch, enthousiast en denk vanuit het perspectief van de opdrachtgever. Ik werk graag samen, ben in staat me eenvoudig aan mijn omgeving aan te passen, toon initiatief en ben erg leergierig."],
			tools: [],
			indexVan: 400,
			subSet: 4,
			myclass: "j4",
			row1: true
		},
		{
			name: "Consultant Risk & Security - ING",
			shortName: "Consultant Risk/Security",
			periode: "okt 2015 - dec 2015",
			description: ["Als Consultant Risk & Security adviseerde Markus over het beveiligen van de kritieke informatie en bedrijfsprocessen op zowel strategisch, tactisch en operationeel niveau. Hij was de brug tussen Business, IT en de Risk afdelingen die technische uitdagingen kan uitleggen op alle niveaus. Hij bewaakte het referentiekader voor het inrichten van de beheerprocessen (ITIL). Tevens hielp hij bij het ontwerpen en/of implementeren van processen, die de continuiteit van User Access waarborgen op het moment dat er een incident / crisis uitbreekt.", "Beveiliging op het gebied van vertrouwelijkheid, integriteit en beschikbaarheid voerde de boventoon bij de User Access omgeving. Markus was verantwoordelijk voor vijf applicaties. In de drie maanden dat hij zijn visie heeft uitgewerkt heeft hij de veiligheid van de applicaties substantieel verhoogd. Dit heeft hij gedaan door: <ul class=\"normal\"> <li>Ontwerpen wachtwoord reset procedures voor High Privileged Accounts</li><li>Ontwerpen Security Event monitoring</li><li>Oplossen audit / security bevindingen</li><li>Schrijven security en compliance documenten</li><li>Verbeterplannen schrijven voor security risico's</li></ul>"],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "CMDB", "Aveksa", "Scrum", "DevOps", "Backup and Restore", "Disaster Recovery", "Governance", "Security Event Monitoring", "Security", "HPSC", "Operational Security Guidelines", "Identity- and  Access Management", "Dynamic/Static Code review", "Auditing", "ITIL"],
			indexVan: 410,
			subSet: 4,
			myclass: "j4s1",
			row1: false
		},
		{
			name: "Scrum Master DevOps Authentication - ING",
			shortName: "Scrum master",
			periode: "dec 2014 - sep 2015",
			description: ["Als Scrum Master begeleidde / hielp Markus het DevOps team door er voor te zorgen dat het juiste Scrum proces gevolgd werd. Hij coachte teamleden in de Agile/Scrum principes en promootte zelf regulering van het team. Hij regelde alle vergaderingen. Ook regelde hij de voorzieningen zoals een werkruimte, hardware en software. Hij zorgde ervoor dat het team niet lastig gevallen wordt door derden die met extra eisen tussendoor komen of die bijvoorbeeld tijdelijk mensen nodig hebben uit het team.","Markus was volledig toegewezen aan &#233;&#233;n enkel team omdat zijn technische kennis voor het team van grote waarde was. Hij kon het team op die manier niet alleen helpen het scrumproces te volgen maar ook coachen op technisch en security gebied.","Daarnaast was Markus nauw betrokken bij ondersteunen van de Product Owner en hielp hij het management team inzien waar zij het team konden ondersteunen of waar zij juist het team vrijer moesten laten."],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "HPSC", "CMDB", "Aveksa", "GIT", "Fitnesse", "Selenium", "WebEx", "Incident Management", "Oracle Enterprise Manager", "Websphere Console", "NetBeans IDE", "SSH", "Notepad++", "Oracle SQL Developer", "Softerra LDAP Administrator", "Putty", "Scrum", "DevOps", "Backup and Restore", "Security Event Monitoring", "Java", "Auditing", "ITIL", "Operational Security Guidelines", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "Data masking", "Testing", "Applicatie beheer", "Operationeel beheer", "JBoss", "Coaching", "Javascript", "HTML", "VBscript", "Shell Script", "Oracle", "WebSphere"],
			indexVan: 420,
			subSet: 4,
			myclass: "j4s2",
			row1: false
		},
		{
			name: "Product Owner Scrumteams - ING",
			shortName: "Product Owner",
			periode: "mei 2014 - nov 2014",
			description: ["Markus verzamelde input van stakeholders, data-analyse en feedback van de business. En tegelijk ging hij aan de slag met het (door)ontwikkelen van een visie voor zijn focusgebied (Aveksa). Om vervolgens zijn vergaarde input en visie om te zetten in een roadmap en een backlog. Samen met zijn teams was hij verantwoordelijk voor het uitvoeren en opleveren van een betrouwbare User Access Management systeem.", "De teams van Markus werkte nauw samen met het test team. Dit team was bezig de regressietesten in te voeren in Selenium en Fitnesse. Vooral het team dat uit analisten en architecten bestond waren druk bezig om beleid uit te zetten voor de automatisering.", "Markus verzamelde input van stakeholders, data-analyse en feedback van de business. Tegelijk ging hij aan de slag met het (door)ontwikkelen van een visie voor zijn focusgebied (Aveksa), om vervolgens zijn vergaarde input en visie om te zetten in een roadmap en een backlog. Samen met zijn teams was hij verantwoordelijk voor het uitvoeren en opleveren van een betrouwbare User Access Management systeem.", "Markus was verantwoordelijk voor 2 scrum teams. Zijn team bestonden uit Developers, Operationele medewerkers, Business Analisten en  Architecten.  Samen verbeterden en vernieuwden zij in sprints de applicaties van User Access Management. En als Product Owner zette Markus samen met het team en de stakeholders de koers uit voor de focus."],
			tools: ["OCD", "Office", "Jira", "Confluence", "SharePoint", "HPSC", "Aveksa", "GIT", "WebEx", "IBM Tivoli Identity Manager", "Scrum", "DevOps", "Backup and Restore", "Auditing", "ITIL", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "Testing", "Applicatie beheer", "Operationeel beheer", "Incident Management", "Roadmap"],
			indexVan: 430,
			subSet: 4,
			myclass: "j4s3",
			row1: false
		},
		{
			name: "Identity- Access en Security Specialist in DevOps / Scrum team  - ING",
			shortName: "Dev engineer DevOps",
			periode: "sep 2013 - sep 2015",
			description: ["Na ruim 5 jaar betrokken te zijn bij de IAM oplossing van ING ben ik gevraagd toe te treden tot het team dat de exercitie doet om Een nieuw IAM product te implementeren. Mijn ruime ervaring met de processen, de huidige techniek en procedures maakte mij een uitstekende aanvulling van het team." ,"Ik heb binnen het team veel verschillende aspecten kunnen uitwerken.","Ten eerste het technische vlak: Ik heb verschillende workflows gebouwd, connecties gemaakt met verschillende platformen en regels gemaakt die autorisatiebeheer moeten automatiseren. Samen met het team is een appliance beheert en later omgebouwd naar een PAAS omgeving. Beheer van Oracle; Websphere en Unix viel tevens onder de verantwoordelijkheden van het team.", "Ten tweede het operationele vlak: Belangrijk deel van een DevOps team is ook het dagelijks beheer. Binnen het team werd operationeel werk onderling verdeeld. Incident management; change management; testen en contact met de interne klanten.", "Ten slotte het security vlak: Niet alleen vereist agile/scrum het maken en borgen van afspraken, ook het feit dat we een identity- en access management omgeving beheren voor de autorisaties van een bank vereisen dat er compliant gehandeld wordt en dat de applicatie in control moet zijn. Hiervoor heb ik veel werk verzet. Het in control komen en vooral blijven. Enkele zaken die hij heeft opgeleverd: Operational Security Guidelines; Distaster and recovery plan en Backup en Restore procedures.", "Tijdens deze periode heb ik bewezen een echte troubleshooter te zijn en heb daarbij ook een aantal andere rollen gehad binnen de DevOps teams (Product Owner en Scrummaster)."],
			tools: ["..","..."],
			indexVan: 440,
			subSet: 4,
			myclass: "j4s4",
			row1: false
		},
		{
			name: "Teamleader Entitlement Services (CDC ING/UAS) - Atos",
			shortName: "Teamleider IAM dev team",
			periode: "sep 2011 - sep 2013",
			description: ["Als teamleider stuurde Markus de technische medewerkers van de afdeling Entitlement Services aan. Het ging om een afdelingen die voor ING de Identity- en Access Management applicatie beheerde. Hij zag toe op de werkzaamheden van de medewerkers en begeleidde ze zowel als team en als individu met het doel het maximale uit de medewerkers en het team te halen. Daarnaast voerde hij HR taken uit zoals: werkoverleg, &#233;&#233;n-op-&#233;&#233;n gesprekken en verzorgde hij GROW-sessies.", "Ook was hij verantwoordelijk voor het opzetten van het changeproces en opzetten van de planning hiervan. Hij zorgde ervoor dat de bezetting van de afdeling aansloot bij het werkaanbod.", "Voor het team bewaakte hij de SLA afspraken, verzorgde rapportages en schreef de Service Component Description. Markus onderhield nauw contact met ING in verschillende overleggen en koppelde de feedback terug naar zijn medewerkers.", "Zijn rol was coachende en adviserende, hij wist de juiste structuur systematisch toe te passen en hij had een stevige visie op het productieproces. Door zijn inzet bracht hij niet alleen zijn afdeling op een hoger plan maar hielp hij de organisatie als geheel ook vooruit!"],
			tools: ["Auditing", "ITIL", "Identity- and  Access Management", "Governance", "UNIX", "LDAP", "AD", "RACF", "CDS", "SSH", "Testing", "Applicatie beheer", "Operationeel beheer", "Incident Management", "Javascript", "Java", "HTML", "VBscript", "Oracle", "WebSphere", "GROW", "Service Component Description", "Human Resourcing", "Service Level Agreement", "Key Performance Indicators", "Coaching"],
			indexVan: 450,
			subSet: 4,
			myclass: "j4s5",
			row1: false
		},
		{
			name: "Change- en Release Coordinator ITIM - Atos",
			shortName: "Change- release mgr",
			periode: "mrt 2011 - okt 2013",
			description: ["De CDC ING beheert voor ING Groep Nederland de Identity Management tool IBM Tivoli Identity Manager (ITIM). Deze tool wordt gebruikt voor account management en autorisatiebeheer. Atos onderhield het programma; workflows; adapters naar verschillende platformen; de Java schil voor eindgebruikers en de Rapportages. Deze waren allen aan changes onderhevig.", "Markus onderhield direct contact met de functioneel eigenaar en de direct stakeholders van ITIM. Dit gebeurde in het Change Advisory Board. In dit overleg werden nieuwe changes besproken en de prioriteit bepaald. Tevens koppelde Markus wekelijks de voortgang terug van de lopende changes, testresultaten en releases.", "Daar naast had Markus op een aantal momenten per week overleg met het team. In een korte sessie werd besproken wat de voortgang was en of de deadline nog haalbaar was. Informatie vanuit de CAB sessies werd hier met het team besproken. Op basis van de informatie kon Markus weer het CAB adviseren.", "Maandelijks werd samen met het team de nieuwe release besproken. In een simpele schatting bepaalde het team wat zij deze maand konden opleveren, testen en in productie konden zetten. Markus zorgde ervoor dat in een kort tijdsbestek een planning werd opgeleverd die aansloot op de prioriteitenlijst en de haalbaarheid.", "Ten slotte was Markus verantwoordelijk voor de release planning en hield de voortgang daarvan bij. In iteraties van een maand werden de releases voorbereid en eens per maand werd dan de release doorgevoerd. Bij de release planning hoorde ook het plannen van resources ten behoeve van de release, ketentests, onderhoud aan de DTA omgeving en co&#246;rdinatie van de test-, acceptatie- en productiereleases."],
			tools: ["SDM", "Office", "SharePoint", "HP Service Center", "IBM Tivoli Identity Manager", "Governance", "Auditing", "ITIL", "Incident Management", "Release Management", "DTAP" ],
			indexVan: 460,
			subSet: 4,
			myclass: "j4s6",
			row1: false
		},
		{
			name: "Agile Software Development Coach",
			shortName: "Agile Coach",
			periode: "jan 2016 - Heden",
			description: ["Tussen 2013 en 2016 ben ik nauw betrokken geweest bij een Scrum project binnen ING. Als Product Owner en Scrum Master heb ik geholpen het Scrum proces in te richten binnen de User Access afdeling. Daarna heb ik bij ABN Amro tot eind 2017 meerdere team geholpen hun agile manier van werkern verder te verbeteren.", "Als CI/CD coach bij ABN Amro heb ik niet alleen teams gecoacht, maar ook standaarden gemaakt op het gebied van Trunk Based Development, heb ik samen met het team grote bijeenkomsten opgezet om successen vanuit teams te delen met andere teams en heb ik bootcamps, trainingen en informatiesessies gegeven aan teamleden. Als Scrum Master, begeleider van een aantal projecten en als teamleider zijn vooral mijn coachende vaardigheden ontwikkeld. Ik heb onder andere junior medewerkers geholpen zich te ontwikkelen tot BI specialisten en ge&#239;nspireerd zich te blijven verbeteren op hun vakgebied. E&#233;n van mijn grootste projecten was als begeleider van een mindset verander traject, hier heb ik een groep van 250 managers en 5000 medewerkers gecoacht om een grootschalige cultuur omslag te maken. Als Scrum Master heb ik bewezen dat ik een Scrum Team kan coachen in de principes van Agile/Scrum en zorgde ik ervoor dat het team het juiste Scrum proces volgde.","Ik ben een groot fan van de Agile manier van werken. Binnen Atos heb ik het management ge&#239;nspireerd op een Agile manier te werken. Mede hierdoor ontstonden op meerdere strategische niveaus Scrum Teams, die onderling samenwerkten om de visie van een klant specifiek opleidingsproject waar te maken. Het bereiken van dit resultaat gaf mij veel voldoening"],
			tools: [],
			indexVan: 500,
			subSet: 5,
			myclass: "j5",
			row1: true
		},
		{
			name: "Agile coach CI/CD Stack - ABN Amro",
			shortName: "Agile CI/CD Coach",
			periode: "jun 2016 - heden",
			description: ["Binnen IT solutions werd een CICD-expert (continuous integration continuous delivery) gezocht, die naast heeft naast technische kennis tevens uitstekende coaching kwaliteiten heeft.", "Een Centers of Expertise (CoE) werkt samen met projecten om er zo voor te zorgen dat nieuwe of gewijzigde applicaties en infrastructuur op een correcte manier worden ge&#239;mplementeerd. Dit maakt de rol van een CoE medewerker in het project complex, enerzijds wordt het project met inbreng van expertise geholpen, anderzijds kunnen de standaarden die gevolgd moeten worden een complicerende en beperkende factor voor het project zijn. Daarnaast zijn ze onderdeel van de formele Quality Assurance binnen het eigen aandachtsgebied", "Bij binnenkomst van Markus werd Agil/Scrum binnen bepaalde onderdelen van de bank uitgerold, naast houding en gedrag is automatisering van de processen voorwaardelijk voor een succesvolle uitrol.", "Als Agile coach CI/CD Stack was Markus verantwoordelijk voor: <ul class=\"normal\"> <li><b>Coaching</b>: een succesvolle grootschalige implementatie van CICD gaat voor een groot deel over houding en gedrag, gecombineerd met een gedegen technische onderbouwing. De kandidaat moet beide uitstekend kunnen overdragen aan teams van zeer diverse pluimage.</li><li><b>Flexibiliteit en inventiviteit</b>: de CICD uitrol binnen ABN AMRO gaat gepaard met de Agile uitrol. Veel in beide trajecten is onzeker. De kandidaat moet goed met die onzekerheid om kunnen gaan en inventief kunnen inspringen op de snel wijzigende omstandigheden.</li><li><b>IT autoriteit</b>: de kandidaat moet een zeer ervaren IT-er met hands-on kennis van verschillende technieken zijn en moet daarin door zijn peers als autoriteit erkend worden.</li></ul>"],
			tools: ["Jira", "Office", "Jenkins", "SonarQube", "HP Fortify", "Maven", "Scrum", "DevOps", "Agile", "Consulting", "Interview", "Kennisoverdracht", "Coaching", "Continuous Integration", "Continuous Delivery", "Unit testing", "Code Quality", "VBA", "Bootcamps", "Workshops", "XL Release", "XL Deploy", "uDeploy"],
			indexVan: 510,
			subSet: 5,
			myclass: "j5s1",
			row1: false
		},
		{
			name: "Agile coach en adviseur - Atos",
			shortName: "Agile CI/CD Coach",
			periode: "jan 2016 - jun 2016",
			description: ["Als Agile coach stimuleerde en adviseerde Markus over de Agile manier van werken binnen Atos en bij diverse opdrachtgevers.", "Beginnend in een start-up innovaties team van waar Markus zijn ervaring met Scrum en DevOps gebruikte om het Scrum proces te stroomlijnen. Hij gaf training in Jira en \"Scrum fundamentals\" waarin hij mensen inspireerde om hun kennis verder te verdiepen, dit resulteerde erin dat een aantal van hen zich gingen voorbereiden voor hun eigen PSM1 certificaat.", "Voor diverse opdrachtgevers analyseerde Markus de huidige Agile processen en identificeerde knelpunten. Hij adviseerde hoe deze knelpunten op te lossen en schreef plannen om de huidige processen te verbeteren. Voor een van de klanten zette hij een compleet plan op om de klant toe te voegen binnen de DevOps structuur.", "Intern Atos heeft Markus een groep managers ondersteund om ook een klant specifiek opleidingsproject op een Scrum wijze aan te pakken. Hij zorgde voor structuur en gelaagdheid zodat de hoogste management laag bezig was met de portfolio en roadmap, de lagere lagen werkten hun specifieke gebieden uit. Op deze manier ontstonden meerdere Scrum Teams. Markus stond ze bij door de Scrum methodiek te bewaken en heeft geholpen een Jira board op te zetten."],
			tools: ["Jira", "Office", "Scrum", "DevOps", "Agile", "Consulting", "Interview" ,"Kennisoverdracht" , "Coaching"],
			indexVan: 520,
			subSet: 5,
			myclass: "j5s2",
			row1: false
		},
		{
			name: "Begeleider \"Transforward to .....\" Project - Atos",
			shortName: "Begeleider change project",
			periode: "apr 2014 - dec 2014",
			description: ["Transforward to ..... is een groot project geweest om intern een cultuur en mindset verandering teweeg te brengen onder de medewerkers van MS. Het hele project bestond uit 3 fasen.", "In totaal moest de organisatie van 5000 man veranderen. Dit gebeurde door Het MT, alle 250 managers en 1500 medewerkers te betrekken in het verandertraject. Methoden <ul class=\"normal\"><li>&raquo; Bewustwordings sessies</li><li>&raquo; Open space sessies</li><li>&raquo; Process verbeter trajecten</li></ul>", "Als &#233;&#233;n van de begeleiders zorgde Markus ervoor dat het MT, alle managers van MS en een grote groep medewerkers door deze fase werd geleid. Naast betrokken te zijn bij alle sessies was hij ook nauw betrokken bij alle activiteiten buiten de sessies. Hierin was het zijn taak om deelnemers te coachen en bewust te zijn van de doelstellingen en afspraken.", "Als begeleiders team samen met de docenten hebben we een mooi resultaat neer gezet. Uit een Denison scan is gebleken dat de koers in de juiste richting is aangepast."],
			tools: ["Management Trechter", "Cultural Web Assessment", "SCARF Model", "Sfeer van Invloed", "Persoonlijksheidscirkel", "Interview", "Kennisoverdracht", "Coaching"],
			indexVan: 530,
			subSet: 5,
			myclass: "j5s3",
			row1: false
		},
		{
			name: "CDC ING Kennis Motivator - Atos",
			shortName: "kennismotivator",
			periode: "nov 2012 - okt 2013",
			description: ["Binnen het klantdomein van ING bij Atos is een opleidingsproject gestart om processen en mensen communicatief sterker en meer klantgericht te maken. Het project werd op basis van de Lean principes uitgewerkt. Binnen de het project was ook een groep medewerkers met de taak om de kennis en handvatten toe passen, kennis over te dragen, opleiding te geven en processen te bewaken.", "Als motivator was Markus verantwoordelijk voor drie teams van in totaal 30 mensen. De kennis werd overgebracht in grote sessies en online trainingen, maar ook via persoonlijke begeleiding. Om de medewerkers van CDC ING met de materie te blijven oefenen organiseerde Markus bijeenkomsten waar medewerkers in een vertrouwde omgeving konden oefenen. Medewerkers kregen de verantwoordelijkheid zelf sessies te organiseren, werden gecoacht en kregen extra theorie gepresenteerd."],
			tools: ["Office", "Lean", "Interview", "Kennisoverdracht", "Coaching"],
			indexVan: 540,
			subSet: 5,
			myclass: "j5s4",
			row1: false
		}
	]
